# Site wide configuration
destination: docs
url: 'https://career.rossgodwin.com'
baseurl: ''
lang: en

# Analytics
google_analytics_measurement_id: G-X190CB39TW

# Jekyll configuration
show_drafts: false
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
include:
  - _pages
exclude:
  - .bundle
  - .jekyll-cache
  - .gitignore
  - .project
  - _drafts
  - docs/
  - Gemfile
  - Gemfile.lock
  - README.md
  - other
  - vendor/bundle/

excerpt_separator: <!--more-->

sass:
  style: :compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Plugins
gems:
  - jekyll-feed
  - jekyll-liquify

plugins:
  - jekyll-gist
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      include-seo: false
      include-seo-og: false
  - scope:
      path: information-technology/*
    values:
      include-seo: false
  - scope:
      path: docs/*
    values:
      sitemap: false
  - scope:
      path: assets/*
    values:
      sitemap: false