# Site wide configuration
destination: docs
url: 'https://career.rossgodwin.com'
baseurl: ''
lang: en

# Analytics
google_analytics_measurement_id: G-X190CB39TW

# Jekyll configuration
show_drafts: false
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
include:
  - _pages
exclude:
  - .bundle
  - .jekyll-cache
  - .gitignore
  - .project
  - _drafts
  - docs/
  - Gemfile
  - Gemfile.lock
  - README.md
  - other
  - Photoshop/
  - vendor/bundle/

excerpt_separator: <!--more-->

sass:
  style: :compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Collections
collections_dir: articles
collections:
  information-technology:
    output: true
    permalink: /articles/:collection/:path/

# Plugins
gems:
  - jekyll-feed
  - jekyll-liquify

plugins:
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      include-seo: true
      include-seo-og: false
  - scope:
      path: information-technology/*
    values:
      include-seo: false
  - scope:
      path: docs/*
    values:
      sitemap: false
  - scope:
      path: assets/*
    values:
      sitemap: false

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  tags:
    enabled: true
    layouts:
      - autopage_tags.html
    permalink: /articles/tag/:tag
  categories:
    enabled: false
    layouts:
      - autopage_category.html
  collections:
    enabled: false
    slugify:
      mode: 'ascii'
      cased: true